=== hmrc/self-assessment-api/public/api/conf/1.0/schemas/uk-property/UKProperty.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "UK Properties business",
  "type": "object",
  "properties": {
    "id": {
      "title": "ID",
      "description": "Unique identifier",
      "type": "string"
    },
    "propertiesType": {
      "title": "Properties business type",
      "description": "FHL if it's a furnished-holiday-letting business, otherwise OTHER",
      "type": "string",
      "enum": [
        "FHL",
        "OTHER"
      ]
    },
    "accountingPeriod": {
      "$ref": "../AccountingPeriod.json"
    },
    "accountingType": {
      "title": "Accounting type",
      "description": "CASH if you used the cash basis, money actually received and paid out, to calculate your income and expenses. Otherwise ACCRUAL.",
      "type": "string",
      "enum": [
        "CASH",
        "ACCRUAL"
      ]
    }
  },
  "required": [
    "propertiesType",
    "accountingType"
  ],
  "additionalProperties": false
}

=== hmrc/self-assessment-api/public/api/conf/1.0/examples/uk-property/UKProperties.json
[{
  "id": "furnished-holiday-lettings",
  "propertiesType": "FHL",
  "accountingPeriod": {
    "start": "2017-04-06",
    "end": "2018-04-05"
  },
  "accountingType": "CASH"
},
{
  "id": "other",
  "propertiesType": "OTHER",
  "accountingPeriod": {
    "start": "2017-04-06",
    "end": "2018-04-05"
  },
  "accountingType": "CASH"
}]
