=== hmrc/self-assessment-api/public/api/conf/1.0/schemas/furnished-holiday-letting/Period.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Period",
  "properties": {
    "id": {
      "title": "ID",
      "description": "Unique identifier",
      "type": "string"
    },
    "from": {
      "title": "From date",
      "type": "string",
      "format": "date"
    },
    "to": {
      "title": "To date",
      "type": "string",
      "format": "date"
    },
    "incomes": {
      "$ref": "Incomes.json"
    },
    "expenses": {
      "$ref": "Expenses.json"
    },
    "balancingCharge": {
      "title": "Balancing charge",
      "type": "number",
      "minimum": 0
    },
    "privateUseAdjustment": {
      "title": "Private use adjustment",
      "type": "number",
      "minimum": 0
    }
  },
  "required": [
    "from",
    "to"
  ],
  "additonalProperties": false
}

=== hmrc/self-assessment-api/public/api/conf/2.0/examples/uk-properties/other/Period.json
{
  "from": "2017-04-06",
  "to": "2017-07-04",
  "incomes": {
    "rentIncome": {
      "amount": 100.25,
      "taxDeducted": 100.25
    },
    "premiumsOfLeaseGrant": { "amount": 100.25 },
    "reversePremiums": { "amount": 100.25 },
    "otherPropertyIncome": {"amount": 100.25},
    "rarRentReceived": {"amount": 100.25}
  },
  "expenses": {
    "premisesRunningCosts": { "amount": 100.25 },
    "repairsAndMaintenance": { "amount": 100.25 },
    "financialCosts": { "amount": 200.25 },
    "professionalFees": { "amount": 100.25 },
    "travelCosts": { "amount": 100.25 },
    "costOfServices": { "amount": 100.25 },
    "residentialFinancialCost": { "amount": 200.25 },
    "broughtFwdResidentialFinancialCost": { "amount": 100.25 },
    "other": { "amount": 100.25 },
    "rarReliefClaimed": { "amount": 100.25 }
  }
}

=== hmrc/self-assessment-api/public/api/conf/2.0/examples/uk-properties/fhl/Period.json
{
  "from": "2017-04-06",
  "to": "2017-07-04",
  "incomes": {
    "rentIncome": {
      "amount": 100.25,
      "taxDeducted": 100.25
    },
    "rarRentReceived" : { "amount" : 100.44}
  },
  "expenses": {
    "premisesRunningCosts": { "amount": 100.25 },
    "repairsAndMaintenance": { "amount": 100.25 },
    "financialCosts": { "amount": 100.25 },
    "professionalFees": { "amount": 100.25 },
    "costOfServices": { "amount": 100.25},
    "travelCosts": { "amount": 100.25},
    "other": { "amount": 100.25 },
    "rarReliefClaimed" : { "amount" : 100.44 }
  }
}

=== hmrc/self-assessment-api/public/api/conf/1.0/examples/uk-properties/fhl/Period.json
{
  "from": "2016-04-06",
  "to": "2016-07-04",
  "incomes": {
    "rentIncome": 100.25
  },
  "expenses": {
    "premisesRunningCosts": 100.25,
    "repairsAndMaintenance": 100.25,
    "financialCosts": 100.25,
    "professionalFees": 100.25,
    "costOfServices": 100.25,
    "other": 100.25
  }
}

=== hmrc/self-assessment-api/resources/public/api/conf/2.0/examples/uk-properties/other/Period2.json
{
  "from": "2018-04-06",
  "to": "2018-07-05",
  "incomes": {
    "rentIncome": {
      "amount": 100.25,
      "taxDeducted": 100.25
    },
    "premiumsOfLeaseGrant": { "amount": 100.25 },
    "reversePremiums": { "amount": 100.25 },
    "otherPropertyIncome": { "amount": 100.25 },
    "rarRentReceived": { "amount": 100.25 }
  },
  "expenses": {
    "consolidatedExpenses": { "amount": 100.25 },
    "residentialFinancialCost": { "amount": 100.25 },
    "broughtFwdResidentialFinancialCost": { "amount": 100.25 }
  }
}
