=== hmrc/self-assessment-api/public/api/conf/1.0/schemas/self-employment/PeriodSummary.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Period summary for self-employment",
  "properties": {
    "id": {
      "title": "ID",
      "description": "Unique identifier",
      "type": "string"
    },
    "from": {
      "title": "From date",
      "description": "ISO-8601, YYYY-MM-DD",
      "type": "string"
    },
    "to": {
      "title": "To date",
      "description": "ISO-8601, YYYY-MM-DD",
      "type": "string"
    },
    "incomes": {
      "type": "object",
      "properties": {
        "turnover": {
          "title": "Turnover",
          "description": "The takings, fees, sales or money earned by your business",
          "type": "number",
          "minimum": 0,
          "default": 0
        },
        "other": {
          "title": "Other",
          "description": "Any other business income not included in turnover",
          "type": "number",
          "minimum": 0,
          "default": 0
        }
      }
    },
    "expenses": {
      "type": "object",
      "properties": {
        "coGBought": {
          "title": "Cost of goods bought",
          "description": "Cost of goods bought for resale or goods used",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "cisPaymentsToSubcontractors": {
          "title": "Construction industry - payments to subcontractors",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "staffCosts": {
          "title": "Staff costs",
          "description": "Wages, salaries and other staff costs",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "travelCosts": {
          "title": "Travel costs",
          "description": "Car, van and travel expenses",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "premisesRunningCosts": {
          "title": "Premises running costs",
          "description": "Rent, rates, power and insurance costs",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "maintenanceCosts": {
          "title": "Maintenance costs",
          "description": "Repairs and renewals of property and equipment",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "adminCosts": {
          "title": "Admin costs",
          "description": "Phone, fax, stationery and other office costs",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "advertisingCosts": {
          "title": "Advertising costs",
          "description": "Advertising and business entertainment costs",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "interest": {
          "title": "Interest",
          "description": "Interest on bank and other loans",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "financialCharges": {
          "title": "Financial charges",
          "description": "Bank, credit card and other financial charges",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "badDebt": {
          "title": "Bad debt",
          "description": "Irrecoverable debts written off",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "professionalFees": {
          "title": "Professional fees",
          "description": "Accountancy, legal and other professional fees",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "depreciation": {
          "title": "Depreciation",
          "description": "Depreciation and loss/profit on sales of assets",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        },
        "other": {
          "title": "Other",
          "description": "Other business expenses",
          "$ref": "../Expense.json",
          "default": {
            "amount": 0
          }
        }
      }
    },
    "balancingCharges": {
      "type": "object",
      "properties": {
        "bpra": {
          "title": "BPRA",
          "description": "Balancing charge on sale or cessation of business use (only where Business Premises Renovation Allowance has been claimed)",
          "type": "number",
          "minimum": 0,
          "default": 0
        },
        "other": {
          "title": "Other",
          "description": "Balancing charge on sale or cessation of business use (where you have disposed of assets for more than their tax value)",
          "type": "number",
          "minimum": 0,
          "default": 0
        }
      }
    },
    "goodsAndServicesOwnUse": {
      "title": "Goods and services own use",
      "type": "number",
      "minimum": 0,
      "default": 0
    }
  }
}

=== hmrc/self-assessment-api/public/api/conf/1.0/examples/self-employment/CreatePeriodSummaryRequest.json
{
  "from": "06-04-2016",
  "to": "05-07-2016",
  "incomes": {
    "turnover": 100,
    "other": 100
  },
  "expenses": {
    "coGBought": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "cisPaymentsToSubcontractors": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "staffCosts": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "travelCosts": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "premisesRunningCosts": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "maintenanceCosts": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "adminCosts": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "advertisingCosts": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "interest": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "financialCharges": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "badDebt": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "professionalFees": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "depreciation": {
      "amount": 100,
      "disallowableAmount": 50
    },
    "other": {
      "amount": 100,
      "disallowableAmount": 50
    }
  },
  "balancingCharges": {
    "bpra": 100,
    "other": 100
  },
  "goodsAndServicesOwnUse": 100
}
